version: "3.8"
name: "blockchain_cluster"

services:
  bootstrap:
    container_name: bootstrap
    restart: no
    build: .
    command: python rest.py bootstrap
    volumes:
      - ./source:/source
    ports:
      - "8000:8000"

  client1:
    container_name: client1
    restart: no
    build: .
    command: python rest.py client 1
    depends_on:
      - bootstrap
    volumes:
      - ./source:/source
    ports:
      - "8001:8001"

  client2:
    container_name: client2
    restart: no
    build: .
    command: python rest.py client 2
    depends_on:
      - bootstrap
    volumes:
      - ./source:/source
    ports:
      - "8002:8002"

  client3:
    container_name: client3
    restart: no
    build: .
    command: python rest.py client 3
    depends_on:
      - bootstrap
    volumes:
      - ./source:/source
    ports:
      - "8003:8003"

  client4:
    container_name: client4
    restart: no
    build: .
    command: python rest.py client 4
    depends_on:
      - bootstrap
    volumes:
      - ./source:/source
    ports:
      - "8004:8004"
