version: "3.8"
name: "test"

services:
  test:
    container_name: test
    restart: always
    build: .
    command: python test.py
    volumes:
      - ./source:/source
    ports:
      - "8000:8000"
