version: "3.8"
name: "blockchain_cluster"

x-env-variables: &env-variables
  PARTICIPANTS: 5
  DIFFICULTY: 5
  CAPACITY: 1
  EXPERIMENT_ID: p5-d5-c1

services:
  bootstrap:
    container_name: bootstrap
    restart: no
    build: .
    command: python rest.py bootstrap
    volumes:
      - ../source:/source
      - ../transactions/5nodes/transactions0.txt:/transactions/transactions.txt
      - ../outputs:/outputs
    ports:
      - "8000:8000"
    environment:
      <<: *env-variables
      ID: 0

  client1:
    container_name: client1
    restart: no
    build: .
    command: python rest.py client 1
    depends_on:
      - bootstrap
    volumes:
      - ../source:/source
      - ../transactions/5nodes/transactions1.txt:/transactions/transactions.txt
      - ../outputs:/outputs
    ports:
      - "8001:8001"
    environment:
      <<: *env-variables
      ID: 1

  client2:
    container_name: client2
    restart: no
    build: .
    command: python rest.py client 2
    depends_on:
      - bootstrap
    volumes:
      - ../source:/source
      - ../transactions/5nodes/transactions2.txt:/transactions/transactions.txt
      - ../outputs:/outputs
    ports:
      - "8002:8002"
    environment:
      <<: *env-variables
      ID: 2

  client3:
    container_name: client3
    restart: no
    build: .
    command: python rest.py client 3
    depends_on:
      - bootstrap
    volumes:
      - ../source:/source
      - ../transactions/5nodes/transactions3.txt:/transactions/transactions.txt
      - ../outputs:/outputs
    ports:
      - "8003:8003"
    environment:
      <<: *env-variables
      ID: 3

  client4:
    container_name: client4
    restart: no
    build: .
    command: python rest.py client 4
    depends_on:
      - bootstrap
    volumes:
      - ../source:/source
      - ../transactions/5nodes/transactions4.txt:/transactions/transactions.txt
      - ../outputs:/outputs
    ports:
      - "8004:8004"
    environment:
      <<: *env-variables
      ID: 4
